services:
  zookeeper:
    image: bitnami/zookeeper:3.8  # Update to a newer Zookeeper image
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Allow unauthenticated connections
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.3  # Update to a newer Kafka image
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_MESSAGE_MAX_BYTES=200000000
      - KAFKA_MAX_REQUEST_SIZE=200000000
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:4.0  # Updated Cassandra image
    environment:
      - CASSANDRA_CLUSTER_NAME=Test Cluster
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  ingestion-service:
    build: ./ingestion-service  # Path to your ingestion service Dockerfile
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092  # Use the 'kafka' service name
    restart: always
    ports:
      - "8000:8000"

  processing-service:
    build:
      context: ./processing-service
    depends_on:
      - kafka
      - cassandra
    networks:
      - kafka_network

  data-api-service:
    build:
      context: ./data-api-service
    ports:
      - "8001:8001"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - kafka_network
    environment:
      - CASSANDRA_HOST=cassandra  # The service name 'cassandra' is used as the hostname

volumes:
  cassandra-data:

networks:
  kafka_network:
    driver: bridge
