services:
  zookeeper:
    image: bitnami/zookeeper:3.8  # Update to a newer Zookeeper image
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Allow unauthenticated connections
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.3  # Update to a newer Kafka image
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:4.0  # Updated Cassandra image
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]

  ingestion-service:
    build:
      context: ./ingestion-service
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    networks:
      - kafka_network

  processing-service:
    build:
      context: ./processing-service
    depends_on:
      - kafka
      - cassandra
    networks:
      - kafka_network

  data-api-service:
    build:
      context: ./data-api-service
    ports:
      - "8001:8001"
    depends_on:
      - cassandra
    networks:
      - kafka_network

volumes:
  cassandra-data:

networks:
  kafka_network:
    driver: bridge
